# Generated by Django 2.2.2 on 2019-08-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_useripstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='useripstore',
            name='city',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useripstore',
            name='countryname',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useripstore',
            name='latitude',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useripstore',
            name='longitude',
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useripstore',
            name='regionname',
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
    ]
