# Generated by Django 2.0.5 on 2018-10-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181024_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
            preserve_default=False,
        ),
    ]
